# Generated by Django 5.2.7 on 2025-10-28 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionApariencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primario', models.CharField(default='#00a1ff', max_length=7)),
                ('color_secundario', models.CharField(default='#16cdc7', max_length=7)),
                ('color_fondo', models.CharField(default='#f8fafd', max_length=7)),
                ('familia_fuente', models.CharField(default='Inter', max_length=50)),
                ('tamano_fuente_base', models.PositiveIntegerField(default=14)),
                ('modo_tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=6)),
                ('logo_key', models.CharField(blank=True, max_length=100, null=True)),
                ('tema', models.CharField(default='Por defecto', max_length=50)),
                ('tipo_letra', models.CharField(default='Inter', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_apariencia', to='hoteles.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Configuración de Apariencia',
                'verbose_name_plural': 'Configuraciones de Apariencia',
                'db_table': 'configuracion_apariencia',
            },
        ),
    ]
