# Generated by Django 5.2.7 on 2025-11-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='En periodo de prueba'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Pagado hasta'),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
