# Generated by Django 5.2.7 on 2025-11-18 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0002_alter_habitacion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_anterior', models.DecimalField(decimal_places=2, help_text='Precio antes del cambio', max_digits=10)),
                ('tarifa_nueva', models.DecimalField(decimal_places=2, help_text='Precio después del cambio', max_digits=10)),
                ('confianza', models.DecimalField(decimal_places=2, help_text='Confianza del modelo al momento de aceptación', max_digits=5)),
                ('motivo', models.TextField(help_text='Motivo del cambio de precio')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de aceptación')),
                ('aceptado_por', models.ForeignKey(help_text='Usuario que aceptó la recomendación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_aceptadas', to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Historial de Recomendación',
                'verbose_name_plural': 'Historial de Recomendaciones',
                'ordering': ['-fecha_aceptacion'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_actual', models.DecimalField(decimal_places=2, help_text='Precio actual de la habitación', max_digits=10)),
                ('tarifa_sugerida', models.DecimalField(decimal_places=2, help_text='Precio sugerido por el modelo de IA', max_digits=10)),
                ('confianza', models.DecimalField(decimal_places=2, help_text='Porcentaje de confianza del modelo (0-100)', max_digits=5)),
                ('motivo', models.TextField(help_text='Explicación de por qué se sugiere este precio')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de generación de la recomendación')),
                ('aceptada', models.BooleanField(default=False, help_text='Indica si la recomendación fue aceptada')),
                ('aplicada', models.BooleanField(default=False, help_text='Indica si el precio ya fue aplicado a la habitación')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'Recomendación de Precio',
                'verbose_name_plural': 'Recomendaciones de Precios',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
