# Generated by Django 5.2.7 on 2025-10-27 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to='backups/')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('auto_daily', 'Automático Diario'), ('auto_weekly', 'Automático Semanal'), ('auto_monthly', 'Automático Mensual')], default='manual', max_length=20)),
                ('backup_type', models.CharField(choices=[('full', 'Completo'), ('tenant', 'Por Tenant')], default='tenant', help_text='Tipo de backup realizado', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ok', 'Correcto'), ('error', 'Fallido'), ('en_progreso', 'En Progreso')], default='en_progreso', max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('tamaño_bytes', models.BigIntegerField(default=0, help_text='Tamaño del archivo en bytes')),
                ('duracion_segundos', models.IntegerField(default=0, help_text='Duración del backup en segundos')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant asociado (null para backups completos)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-fecha'],
            },
        ),
    ]
