# Generated by Django 5.2.7 on 2025-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='backups',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='backups/'),
        ),
    ]
