# Generated by Django 5.2.7 on 2025-11-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_backup_backups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='archivo',
            field=models.CharField(help_text='URL de S3 o ruta local del backup', max_length=500),
        ),
    ]
