# Generated by Django 5.2.7 on 2025-10-13 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('descuento_maximo', models.IntegerField(help_text='Porcentaje máximo de descuento permitido (ej: 50 para 50%)')),
                ('activo', models.BooleanField(default=True)),
                ('puntos_por_dolar_descuento', models.IntegerField(help_text='Puntos necesarios para obtener $1 de descuento (ej: 10 puntos = $1)')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fidelizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelizacion.programafidelizacion')),
            ],
        ),
    ]
