# Generated by Django 5.2.7 on 2025-10-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folioestancias', '0001_initial'),
        ('reservas', '0002_initial'),
        ('servicios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_consumo', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('folioestancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folioestancias', to='folioestancias.folioestancia')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'ServicioReserva',
                'verbose_name_plural': 'ServicioReservas',
                'ordering': ['-fecha_consumo'],
                'unique_together': {('reserva', 'servicio')},
            },
        ),
    ]
