# Generated by Django 5.2.7 on 2025-10-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateField()),
                ('hora_checkin', models.TimeField()),
                ('fecha_checkout', models.DateField(blank=True, null=True)),
                ('hora_checkout', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkinout', to='reservas.reserva')),
            ],
            options={
                'db_table': 'check_in_out',
                'ordering': ['-fecha_checkin'],
            },
        ),
    ]
