# Generated by Django 5.2.7 on 2025-10-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folioestancias', '0001_initial'),
        ('reservas', '0002_initial'),
        ('servicios', '0002_delete_servicioreserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosAsociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_consumo', models.DateField()),
                ('folioestancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folioestancias', to='folioestancias.folioestancia')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_servicio', to='servicios.servicio')),
            ],
            options={
                'ordering': ['fecha_consumo'],
            },
        ),
    ]
