# Generated by Django 5.2.7 on 2025-10-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_asociados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosasociados',
            name='fecha_consumo',
            field=models.DateTimeField(),
        ),
    ]
