# Generated by Django 5.2.7 on 2025-10-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_asociados', '0002_alter_serviciosasociados_fecha_consumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciosasociados',
            options={'ordering': ['fecha_servicio']},
        ),
        migrations.RenameField(
            model_name='serviciosasociados',
            old_name='fecha_consumo',
            new_name='fecha_servicio',
        ),
    ]
