# Generated by Django 5.2.7 on 2025-10-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_asociados', '0003_alter_serviciosasociados_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosasociados',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
