# Generated by Django 5.2.7 on 2025-10-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_asociados', '0004_serviciosasociados_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosasociados',
            name='fecha_servicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
