# Generated by Django 5.2.7 on 2025-10-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_asociados', '0005_alter_serviciosasociados_fecha_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosasociados',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20),
        ),
        migrations.AddField(
            model_name='serviciosasociados',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
