# Generated by Django 5.2.7 on 2025-10-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folioestancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', help_text='Estado actual del pago', max_length=20)),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago')),
                ('metodo', models.CharField(help_text='Método de pago utilizado (efectivo, tarjeta, transferencia, etc.)', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Referencia o número de transacción (opcional)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio_estancia', models.ForeignKey(blank=True, help_text='Folio de estancia asociado al pago', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='folioestancias.folioestancia')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha_pago', '-id'],
                'indexes': [models.Index(fields=['estado', 'fecha_pago'], name='pago_estado_ed32ad_idx'), models.Index(fields=['folio_estancia', 'estado'], name='pago_folio_e_cf0c43_idx')],
            },
        ),
    ]
