# Generated by Django 5.2.7 on 2025-10-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True, help_text='Fecha en que se realizó el pago'),
        ),
    ]
