# Generated by Django 5.2.7 on 2025-10-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se realizó el pago'),
        ),
    ]
