# Generated by Django 5.2.7 on 2025-10-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folioestancias', '0001_initial'),
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_consumo', models.DateField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('folioestancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folioestancias', to='folioestancias.folioestancia')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_servicio', to='servicios.servicio')),
            ],
            options={
                'db_table': 'servicio_reserva',
                'ordering': ['fecha_consumo'],
            },
        ),
    ]
