# Generated by Django 5.2.7 on 2025-10-28 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('max_users', models.IntegerField(default=5)),
                ('max_hotels', models.IntegerField(default=1)),
                ('precio', models.FloatField()),
                ('Tipo', models.CharField(choices=[('Mensual', 'mensual'), ('Anual', 'anual'), ('T', 'Trimestral')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('activo', 'activo'), ('vencido', 'vencido'), ('pausado', 'pausado'), ('cancelado', 'cancelado'), ('prueba', 'prueba')], max_length=20)),
                ('inicio_periodo', models.DateField()),
                ('fin_periodo', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
    ]
