# Generated by Django 5.2.7 on 2025-10-28 01:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotels', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('users', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='core.tenant')),
            ],
        ),
    ]
