# Generated by Django 5.2.7 on 2025-10-28 04:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('suscripciones', '0002_tenantusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='max_hotels',
            new_name='max_hoteles',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='max_users',
            new_name='max_usuarios',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='status',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='UsoTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoteles', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('usuarios', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ultima_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uso', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Uso de Tenant',
                'verbose_name_plural': 'Usos de Tenants',
            },
        ),
        migrations.DeleteModel(
            name='TenantUsage',
        ),
    ]
