# Generated by Django 5.2.7 on 2025-10-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_rename_is_active_plan_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tipo',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Anual', 'Anual'), ('Trimestral', 'Trimestral')], max_length=12),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado'), ('prueba', 'Prueba')], max_length=20),
        ),
    ]
