# Generated by Django 5.2.7 on 2025-10-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0004_alter_plan_tipo_alter_suscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
