# Generated by Django 5.2.7 on 2025-10-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_hotels', 'Can manage hotels'), ('can_manage_rooms', 'Can manage rooms'), ('can_view_reports', 'Can view reports'), ('can_manage_bookings', 'Can manage bookings'), ('can_manage_users', 'Can manage users')]},
        ),
    ]
