# Generated by Django 5.2.7 on 2025-11-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Token FCM para notificaciones push de Firebase', max_length=255, null=True),
        ),
    ]
