# Generated by Django 5.2.7 on 2025-11-19 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
        ('usuarios', '0004_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel al que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='hoteles.hotel'),
        ),
    ]
